### PR TITLE
feat: 1.login user info store, 2.add loging.ts

### PR DESCRIPTION
**Pull request by ekkotest**
# Description & Technical Solution

1. Optimize login and support persistence (refresh will not be lost)
2. Add the loading effect of page switching
3. tableview page optimization style, sidebar optimization style
# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] Already rebased against main branch.

# Screenshots
image

Provide screenshots or videos of the changes made if any.

### CODE REVIEW

**Comment by kankoyan** [comment]
能简短讲一下改了什么吗

**Comment by ekkotest** [comment]
> 能简短讲一下改了什么吗

1.优化登录，支持持久化（刷新依然不会丢失）
2.新增页面切换的loading效果
3.tableview页面优化样式，侧边栏优化样式

**Comment by kankoyan** [comment]
感谢感谢

**Review by kankoyan — APPROVED** [review]

**Review by ShuangDa1018 — APPROVED** [review]
ok

**Pull request merged**
